package model;
// Generated May 7, 2024 9:27:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao  implements java.io.Serializable {


     private int id;
     private String descricao;
     private BigDecimal peso;
     private Set realizas = new HashSet(0);

    public Avaliacao() {
    }

	
    public Avaliacao(int id) {
        this.id = id;
    }
    public Avaliacao(int id, String descricao, BigDecimal peso, Set realizas) {
       this.id = id;
       this.descricao = descricao;
       this.peso = peso;
       this.realizas = realizas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }

    @Override
    public String toString() {
        return "Avaliacao{" + "id=" + id + ", descricao=" + descricao + ", peso=" + peso + ", realizas=" + realizas + '}';
    }

    public void setId(BigDecimal id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


