package model;
// Generated May 7, 2024 9:27:04 PM by Hibernate Tools 4.3.1



/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private int id;
     private String nome;
     private Integer chs;
     private Integer credito;

    public Disciplina() {
    }

	
    public Disciplina(int id) {
        this.id = id;
    }
    public Disciplina(int id, String nome, Integer chs, Integer credito) {
       this.id = id;
       this.nome = nome;
       this.chs = chs;
       this.credito = credito;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getChs() {
        return this.chs;
    }
    
    public void setChs(Integer chs) {
        this.chs = chs;
    }
    public Integer getCredito() {
        return this.credito;
    }
    
    public void setCredito(Integer credito) {
        this.credito = credito;
    }

    @Override
    public String toString() {
        return "Turma{id=" + id + ", nome='" + nome + "'}";
    }


}


